let POSTS = [];

const postsList = document.getElementById('posts-list');
const searchInput = document.getElementById('search-input');
const listView = document.getElementById('list-view');
const postView = document.getElementById('post-view');
const postContent = document.getElementById('post-content');
const homeBtn = document.getElementById('home-btn');
const winTitle = document.getElementById('win-title');

// Automatically find all .md files in /posts directory
async function autoDiscoverPosts() {
  postsList.innerHTML = '<li class="post-item">Scanning C:\\POSTS\\...</li>';
  try {
    const isGithub = window.location.hostname.includes('github.io');
    let files = [];

    if (isGithub) {
      // Pulls post list directly via GitHub API on github.io
      const repoPath = window.location.pathname.split('/')[1] || '';
      const owner = window.location.hostname.split('.')[0];
      const res = await fetch(`https://api.github.com/repos/${owner}/${repoPath}/contents/posts`);
      const data = await res.json();
      files = data.filter(item => item.name.endsWith('.md')).map(item => item.name);
    } else {
      // Reads directory index generated by python3 -m http.server
      const res = await fetch('posts/');
      const text = await res.text();
      const parser = new DOMParser();
      const doc = parser.parseFromString(text, 'text/html');
      const links = Array.from(doc.querySelectorAll('a'));
      files = links.map(a => a.getAttribute('href')).filter(f => f && f.endsWith('.md'));
    }

    // Load each file to extract title/date dynamically from its content
    POSTS = await Promise.all(files.map(async (filename) => {
      const cleanName = filename.replace(/^posts\//, '');
      const filePath = `posts/${cleanName}`;
      const res = await fetch(filePath);
      const text = await res.text();
      
      // Extract first H1 as title, default to filename
      const titleMatch = text.match(/^#\s+(.+)$/m);
      const title = titleMatch ? titleMatch[1] : cleanName.replace('.md', '');

      return {
        title: title,
        file: filePath,
        rawText: text
      };
    }));

    renderPosts();
  } catch (err) {
    postsList.innerHTML = '<li class="post-item" style="color:red;">No posts found or posts/ directory missing.</li>';
  }
}

function renderPosts(filter = '') {
  postsList.innerHTML = '';
  const query = filter.toLowerCase().trim();

  const filtered = POSTS.filter(p => 
    p.title.toLowerCase().includes(query) || p.rawText.toLowerCase().includes(query)
  );

  if (filtered.length === 0) {
    postsList.innerHTML = '<li class="post-item">0 files found.</li>';
    return;
  }

  filtered.forEach(p => {
    const li = document.createElement('li');
    li.className = 'post-item';
    li.innerHTML = `<a onclick="loadPost('${p.file}', '${p.title}')">${p.title}</a>`;
    postsList.appendChild(li);
  });
}

async function loadPost(file, title, pushState = true) {
  try {
    const res = await fetch(file);
    const md = await res.text();
    postContent.innerHTML = marked.parse(md);
    listView.style.display = 'none';
    postView.style.display = 'block';
    winTitle.textContent = `C:\\POSTS\\${title.toUpperCase()}.DOC`;

    // Push state to browser history when opening a post
    if (pushState) {
      history.pushState({ view: 'post', file, title }, '', `#${encodeURIComponent(file)}`);
    }
  } catch (e) {
    postContent.innerHTML = `<p style="color:red;">Error loading file.</p>`;
  }
}

function showHome(pushState = true) {
  postView.style.display = 'none';
  listView.style.display = 'block';
  winTitle.textContent = 'C:\\SYSTEM\\RESEARCH_LOG.EXE';

  // Update browser history back to home root
  if (pushState) {
    history.pushState({ view: 'home' }, '', window.location.pathname);
  }
}

// Handle Browser Back / Forward buttons
window.addEventListener('popstate', (event) => {
  if (event.state && event.state.view === 'post') {
    loadPost(event.state.file, event.state.title, false);
  } else {
    showHome(false);
  }
});

searchInput.addEventListener('input', (e) => renderPosts(e.target.value));
homeBtn.addEventListener('click', (e) => { e.preventDefault(); showHome(); });

// Initialize auto-discovery
autoDiscoverPosts();